### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by timkurvers** [wowserhq/wowser-math#7]
*Gitter (for wowserhq):*

`[![Join chat](https://img.shields.io/badge/gitter-join_chat-blue.svg?style=flat)](https://gitter.im/wowserhq/wowser)`

[![Join chat](https://img.shields.io/badge/gitter-join_chat-blue.svg?style=flat)](https://gitter.im/wowserhq/wowser)

*Code Climate:*

`[![Code Climate](https://img.shields.io/codeclimate/github/wowserhq/wowser-math.svg?style=flat)](https://codeclimate.com/github/wowserhq/wowser-math)`

[![Code Climate](https://img.shields.io/codeclimate/github/wowserhq/wowser-math.svg?style=flat)](https://codeclimate.com/github/wowserhq/wowser-math)

*Code Climate coverage:*

`[![Coverage](https://img.shields.io/codeclimate/coverage/github/wowserhq/wowser-math.svg?style=flat)](https://codeclimate.com/github/wowserhq/wowser=math)`

[![Coverage](https://img.shields.io/codeclimate/coverage/github/wowserhq/wowser-math.svg?style=flat)](https://codeclimate.com/github/wowserhq/wowser-math)

Not entirely sure if these are still up to date, copied them from the main Wowser README.

I'll open a PR a bit later today.

**Comment by timkurvers** [comment]
Looks like Code Climate has a new set of badges:

`[![Maintainability](https://api.codeclimate.com/v1/badges/7ef6d7ffe594af216f6b/maintainability)](https://codeclimate.com/github/wowserhq/wowser-math/maintainability)`

[![Maintainability](https://api.codeclimate.com/v1/badges/7ef6d7ffe594af216f6b/maintainability)](https://codeclimate.com/github/wowserhq/wowser-math/maintainability)

`[![Test Coverage](https://api.codeclimate.com/v1/badges/7ef6d7ffe594af216f6b/test_coverage)](https://codeclimate.com/github/wowserhq/wowser-math/test_coverage)`

[![Test Coverage](https://api.codeclimate.com/v1/badges/7ef6d7ffe594af216f6b/test_coverage)](https://codeclimate.com/github/wowserhq/wowser-math/test_coverage)

---

Maintainability badge on shields.io:

`[![Maintainability](https://img.shields.io/codeclimate/maintainability/github/wowserhq/wowser-math.svg?style=flat)](https://codeclimate.com/github/wowserhq/wowser-math/maintainability)`

[![Maintainability](https://img.shields.io/codeclimate/maintainability/github/wowserhq/wowser-math.svg?style=flat)](https://codeclimate.com/github/wowserhq/wowser-math/maintainability)

**Comment by timkurvers** [comment]
Sigh, didn't mean to close.

**Comment by fallenoak** [comment]
Thumbs up on adding gitter.

Code Climate (coverage) and Travis are already present in the README (from a commit a few days back).

I wasn't sure if there's value in Code Climate's maintainability checks, since math libraries tend to be pretty alien compared to regular code. It also seems to me that these checks aren't much better than just some decent eslint rules, but maybe I'm missing something.

**Comment by timkurvers** [comment]
Yeah that makes total sense! That coverage badge in the current README doesn't seem to work for me, does it work for you @fallenoak ?

**Comment by fallenoak** [comment]
@timkurvers It should be working now.

Github has a privacy proxy server they use to mask loading image URLs present in Markdown files (check the URL and you'll see `camo.githubusercontent.com`).

It looks like that proxy was unable to serve the badge for a bit, but it's working again as of a few minutes ago.
